source 'https://rubygems.org'
ruby '2.2.4'
gem 'rails', '4.0.0'

#gem 'puma'
gem 'pg'
gem 'minitest'
gem 'foreigner'
gem 'simple_form'
gem 'responders'
gem 'enumerate_it'
gem 'has_scope'
gem 'rails_log_stdout',           github: 'heroku/rails_log_stdout'
gem 'rails3_serve_static_assets', github: 'heroku/rails3_serve_static_assets'

