development:
  adapter: postgresql
  encoding: unicode
  database: ima_teste_development
  pool: 5
  username: daniellirio
  password: 120188
test:
  adapter: postgresql
  encoding: unicode
  database: ima_teste_test
  pool: 5
  username: daniellirio
  password: 120188

production:
  adapter: postgresql
  encoding: unicode
  database: ima_teste_production
  pool: 5
  username: daniellirio
  password: 120188